apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-app-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/rohanathan/eks-gha-gitops.git
    targetRevision: main
    path: k8s/overlays/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
